2024-03-31 23:24:09,181 | INFO | test_login.py: 25|------开始执行测试用例，开始时间为：2024-03-31 23:24:09------
2024-03-31 23:24:09,182 | INFO | mysql.py: 15|数据库查询结果为：{'id': 1, 'web': '急救云', 'key': 'url_api', 'value': 'http://systest.whsaviour.com/platform-admin'}
2024-03-31 23:24:09,182 | INFO | test_login.py: 66|正在执行正常登录用例
2024-03-31 23:24:09,184 | INFO | mysql.py: 15|数据库查询结果为：{'id': 1, 'web': '急救云', 'key': 'url_api', 'value': 'http://systest.whsaviour.com/platform-admin'}
2024-03-31 23:24:09,184 | INFO | test_login.py: 66|正在执行密码错误用例
2024-03-31 23:24:09,185 | INFO | mysql.py: 15|数据库查询结果为：{'id': 1, 'web': '急救云', 'key': 'url_api', 'value': 'http://systest.whsaviour.com/platform-admin'}
2024-03-31 23:24:09,185 | INFO | test_login.py: 66|正在执行密码为空用例
2024-03-31 23:24:09,186 | INFO | test_login.py: 28|------执行测试结束，完成时间为：2024-03-31 23:24:09------
2024-03-31 23:24:32,169 | INFO | test_login.py: 25|------开始执行测试用例，开始时间为：2024-03-31 23:24:32------
2024-03-31 23:24:32,170 | INFO | mysql.py: 15|数据库查询结果为：{'id': 1, 'web': '急救云', 'key': 'url_api', 'value': 'http://systest.whsaviour.com/platform-admin'}
2024-03-31 23:24:32,170 | INFO | test_login.py: 66|正在执行用例：正常登录
2024-03-31 23:24:32,170 | INFO | requests_utils.py: 7|发送请求的url为：http://systest.whsaviour.com/platform-admin/sys/login
2024-03-31 23:24:32,170 | INFO | requests_utils.py: 8|发送请求的method为：post
2024-03-31 23:24:32,170 | INFO | requests_utils.py: 9|发送请求的headers为：{'Content-Type': 'application/json'}
2024-03-31 23:24:32,170 | INFO | requests_utils.py: 10|发送请求的data为：{'username': 'admin', 'password': '10010.com'}
2024-03-31 23:24:33,744 | INFO | requests_utils.py: 23|响应状态码为：200
2024-03-31 23:24:33,744 | INFO | requests_utils.py: 24|响应success为：True
2024-03-31 23:24:33,744 | INFO | requests_utils.py: 25|响应message为：登录成功
2024-03-31 23:24:33,748 | INFO | mysql.py: 15|数据库查询结果为：{'id': 1, 'web': '急救云', 'key': 'url_api', 'value': 'http://systest.whsaviour.com/platform-admin'}
2024-03-31 23:24:33,748 | INFO | test_login.py: 66|正在执行用例：密码错误
2024-03-31 23:24:33,748 | INFO | requests_utils.py: 7|发送请求的url为：http://systest.whsaviour.com/platform-admin/sys/login
2024-03-31 23:24:33,748 | INFO | requests_utils.py: 8|发送请求的method为：post
2024-03-31 23:24:33,748 | INFO | requests_utils.py: 9|发送请求的headers为：{'Content-Type': 'application/json'}
2024-03-31 23:24:33,748 | INFO | requests_utils.py: 10|发送请求的data为：{'username': 'admin', 'password': '10010'}
2024-03-31 23:24:33,804 | INFO | requests_utils.py: 23|响应状态码为：200
2024-03-31 23:24:33,805 | INFO | requests_utils.py: 24|响应success为：False
2024-03-31 23:24:33,805 | INFO | requests_utils.py: 25|响应message为：用户名或密码错误
2024-03-31 23:24:33,811 | INFO | mysql.py: 15|数据库查询结果为：{'id': 1, 'web': '急救云', 'key': 'url_api', 'value': 'http://systest.whsaviour.com/platform-admin'}
2024-03-31 23:24:33,811 | INFO | test_login.py: 66|正在执行用例：密码为空
2024-03-31 23:24:33,811 | INFO | requests_utils.py: 7|发送请求的url为：http://systest.whsaviour.com/platform-admin/sys/login
2024-03-31 23:24:33,811 | INFO | requests_utils.py: 8|发送请求的method为：post
2024-03-31 23:24:33,811 | INFO | requests_utils.py: 9|发送请求的headers为：{'Content-Type': 'application/json'}
2024-03-31 23:24:33,811 | INFO | requests_utils.py: 10|发送请求的data为：{'username': 'admin', 'password': ''}
2024-03-31 23:24:33,858 | INFO | requests_utils.py: 23|响应状态码为：200
2024-03-31 23:24:33,858 | INFO | requests_utils.py: 24|响应success为：False
2024-03-31 23:24:33,859 | INFO | requests_utils.py: 25|响应message为：用户名或密码错误
2024-03-31 23:24:33,861 | INFO | test_login.py: 28|------执行测试结束，完成时间为：2024-03-31 23:24:32------
