2024-04-01 20:41:46,337 | INFO | test_login.py: 25|------开始执行测试用例，开始时间为：2024-04-01 20:41:46------
2024-04-01 20:41:46,339 | INFO | mysql.py: 15|数据库查询结果为：{'id': 1, 'web': '急救云', 'key': 'url_api', 'value': 'http://systest.whsaviour.com/platform-admin'}
2024-04-01 20:41:46,339 | INFO | test_login.py: 82|正在执行正常登录用例
2024-04-01 20:41:46,339 | INFO | requests_utils.py: 7|发送请求的url为：http://systest.whsaviour.com/platform-admin/sys/login
2024-04-01 20:41:46,339 | INFO | requests_utils.py: 8|发送请求的method为：post
2024-04-01 20:41:46,339 | INFO | requests_utils.py: 9|发送请求的headers为：{'Content-Type': 'application/json'}
2024-04-01 20:41:46,339 | INFO | requests_utils.py: 10|发送请求的data为：{'username': 'admin', 'password': '10010.com'}
2024-04-01 20:41:46,424 | INFO | requests_utils.py: 23|响应状态码为：200
2024-04-01 20:41:46,424 | INFO | requests_utils.py: 24|响应success为：True
2024-04-01 20:41:46,425 | INFO | requests_utils.py: 25|响应message为：登录成功
2024-04-01 20:41:46,425 | INFO | test_login.py: 84|用例执行成功，请求的结果为：<Response [200]>
2024-04-01 20:41:46,425 | INFO | test_login.py: 91|relation为：，res_data为<Response [200]>
2024-04-01 20:41:46,425 | INFO | test_login.py: 92|case为：{'id': '1', 'web': '急救云', 'module': '登录模块', 'title': '正常登录', 'url': '/sys/login', 'method': 'post', 'headers': '{"Content-Type":"application/json"}', 'token': None, 'request_body': '{\n"username": "admin",\n"password":"10010.com"\n}', 'request_type': 'json', 'relation': '', 'expected_code': 'True', 'isdel': '1'}，res_data为<Response [200]>
2024-04-01 20:41:46,509 | INFO | mysql.py: 28|执行sql语句成功！语句为：insert into test_result_record(`case_id`, `times`, `response`, `result`) values ("1", "2024-04-01 20:41:46", "<Response [200]>", "False") 
2024-04-01 20:41:46,578 | INFO | mysql.py: 15|数据库查询结果为：{'id': 1, 'web': '急救云', 'key': 'url_api', 'value': 'http://systest.whsaviour.com/platform-admin'}
2024-04-01 20:41:46,578 | INFO | test_login.py: 82|正在执行密码错误用例
2024-04-01 20:41:46,578 | INFO | requests_utils.py: 7|发送请求的url为：http://systest.whsaviour.com/platform-admin/sys/login
2024-04-01 20:41:46,578 | INFO | requests_utils.py: 8|发送请求的method为：post
2024-04-01 20:41:46,578 | INFO | requests_utils.py: 9|发送请求的headers为：{'Content-Type': 'application/json'}
2024-04-01 20:41:46,578 | INFO | requests_utils.py: 10|发送请求的data为：{'username': 'admin', 'password': '10010'}
2024-04-01 20:41:46,630 | INFO | requests_utils.py: 23|响应状态码为：200
2024-04-01 20:41:46,630 | INFO | requests_utils.py: 24|响应success为：False
2024-04-01 20:41:46,630 | INFO | requests_utils.py: 25|响应message为：用户名或密码错误
2024-04-01 20:41:46,630 | INFO | test_login.py: 84|用例执行成功，请求的结果为：<Response [200]>
2024-04-01 20:41:46,630 | INFO | test_login.py: 91|relation为：None，res_data为<Response [200]>
2024-04-01 20:41:46,630 | INFO | test_login.py: 92|case为：{'id': '2', 'web': '急救云', 'module': '登录模块', 'title': '密码错误', 'url': '/sys/login', 'method': 'post', 'headers': '{"Content-Type":"application/json"}', 'token': None, 'request_body': '{\n"username": "admin",\n"password":"10010"\n}', 'request_type': 'json', 'relation': None, 'expected_code': 'False', 'isdel': '1'}，res_data为<Response [200]>
2024-04-01 20:41:46,685 | INFO | mysql.py: 28|执行sql语句成功！语句为：insert into test_result_record(`case_id`, `times`, `response`, `result`) values ("2", "2024-04-01 20:41:46", "<Response [200]>", "False") 
2024-04-01 20:41:46,702 | INFO | mysql.py: 15|数据库查询结果为：{'id': 1, 'web': '急救云', 'key': 'url_api', 'value': 'http://systest.whsaviour.com/platform-admin'}
2024-04-01 20:41:46,702 | INFO | test_login.py: 82|正在执行密码为空用例
2024-04-01 20:41:46,702 | INFO | requests_utils.py: 7|发送请求的url为：http://systest.whsaviour.com/platform-admin/sys/login
2024-04-01 20:41:46,702 | INFO | requests_utils.py: 8|发送请求的method为：post
2024-04-01 20:41:46,702 | INFO | requests_utils.py: 9|发送请求的headers为：{'Content-Type': 'application/json'}
2024-04-01 20:41:46,702 | INFO | requests_utils.py: 10|发送请求的data为：{'username': 'admin', 'password': ''}
2024-04-01 20:41:46,751 | INFO | requests_utils.py: 23|响应状态码为：200
2024-04-01 20:41:46,752 | INFO | requests_utils.py: 24|响应success为：False
2024-04-01 20:41:46,752 | INFO | requests_utils.py: 25|响应message为：用户名或密码错误
2024-04-01 20:41:46,752 | INFO | test_login.py: 84|用例执行成功，请求的结果为：<Response [200]>
2024-04-01 20:41:46,752 | INFO | test_login.py: 91|relation为：None，res_data为<Response [200]>
2024-04-01 20:41:46,753 | INFO | test_login.py: 92|case为：{'id': '3', 'web': '急救云', 'module': '登录模块', 'title': '密码为空', 'url': '/sys/login', 'method': 'post', 'headers': '{"Content-Type":"application/json"}', 'token': None, 'request_body': '{\n"username": "admin",\n"password":""\n}', 'request_type': 'json', 'relation': None, 'expected_code': 'False', 'isdel': '1'}，res_data为<Response [200]>
2024-04-01 20:41:46,808 | INFO | mysql.py: 28|执行sql语句成功！语句为：insert into test_result_record(`case_id`, `times`, `response`, `result`) values ("3", "2024-04-01 20:41:46", "<Response [200]>", "False") 
2024-04-01 20:41:46,820 | INFO | test_login.py: 28|------执行测试结束，完成时间为：2024-04-01 20:41:46------
