2024-04-01 22:02:02,352 | INFO | test_login.py: 25|------开始执行测试用例，开始时间为：2024-04-01 22:02:02------
2024-04-01 22:02:02,353 | INFO | mysql.py: 15|数据库查询结果为：{'id': 1, 'web': '急救云', 'key': 'url_api', 'value': 'http://systest.whsaviour.com/platform-admin'}
2024-04-01 22:02:02,354 | INFO | test_login.py: 71|***正在执行正常登录用例***
2024-04-01 22:02:02,354 | INFO | requests_utils.py: 7|发送请求的url为：http://systest.whsaviour.com/platform-admin/sys/login
2024-04-01 22:02:02,354 | INFO | requests_utils.py: 8|发送请求的method为：post
2024-04-01 22:02:02,354 | INFO | requests_utils.py: 9|发送请求的headers为：{'Content-Type': 'application/json'}
2024-04-01 22:02:02,354 | INFO | requests_utils.py: 10|发送请求的data为：{'username': 'admin', 'password': '10010.com'}
2024-04-01 22:02:02,475 | INFO | requests_utils.py: 23|响应状态码为：200
2024-04-01 22:02:02,476 | INFO | requests_utils.py: 24|响应success为：True
2024-04-01 22:02:02,476 | INFO | requests_utils.py: 25|响应message为：登录成功
2024-04-01 22:02:02,477 | INFO | test_login.py: 73|用例执行成功，请求的结果为：{'success': True, 'message': '登录成功', 'code': 200, 'result': {'multi_depart': 0, 'userInfo': {'id': 'e9ca23d68d884d4ebb19d07889727dae', 'username': 'admin', 'realname': '管理员', 'password': 'a2aa542a6313470b', 'salt': 'MT8T61Hf', 'avatar': 'user/20190119/logo-2_1547868176839.png', 'birthday': '2018-12-05', 'sex': 1, 'email': '11@qq.com', 'phone': '18566666661', 'orgCode': 'A01', 'status': 1, 'delFlag': '0', 'createBy': None, 'createTime': '2038-06-21 17:54:10', 'updateBy': 'admin', 'updateTime': '2024-03-22 17:10:37', 'activitiSync': '0'}, 'departs': [], 'token': 'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE3MTE5ODczMjQsInVzZXJuYW1lIjoiYWRtaW4ifQ.zU80d8--FVFhQmc0FPUCsvVruuDByt40fvpxMtDlLNI'}, 'resultList': None, 'timestamp': 1711980124500}
2024-04-01 22:02:02,478 | INFO | test_login.py: 88|用例断言成功
2024-04-01 22:02:02,581 | INFO | mysql.py: 28|执行sql语句成功！
2024-04-01 22:02:02,594 | INFO | mysql.py: 15|数据库查询结果为：{'id': 1, 'web': '急救云', 'key': 'url_api', 'value': 'http://systest.whsaviour.com/platform-admin'}
2024-04-01 22:02:02,595 | INFO | test_login.py: 71|***正在执行密码错误用例***
2024-04-01 22:02:02,595 | INFO | requests_utils.py: 7|发送请求的url为：http://systest.whsaviour.com/platform-admin/sys/login
2024-04-01 22:02:02,595 | INFO | requests_utils.py: 8|发送请求的method为：post
2024-04-01 22:02:02,595 | INFO | requests_utils.py: 9|发送请求的headers为：{'Content-Type': 'application/json'}
2024-04-01 22:02:02,595 | INFO | requests_utils.py: 10|发送请求的data为：{'username': 'admin', 'password': '10010'}
2024-04-01 22:02:02,653 | INFO | requests_utils.py: 23|响应状态码为：200
2024-04-01 22:02:02,653 | INFO | requests_utils.py: 24|响应success为：False
2024-04-01 22:02:02,653 | INFO | requests_utils.py: 25|响应message为：用户名或密码错误
2024-04-01 22:02:02,653 | INFO | test_login.py: 73|用例执行成功，请求的结果为：{'success': False, 'message': '用户名或密码错误', 'code': 500, 'result': None, 'resultList': None, 'timestamp': 1711980124708}
2024-04-01 22:02:02,653 | INFO | test_login.py: 88|用例断言成功
2024-04-01 22:02:02,727 | INFO | mysql.py: 28|执行sql语句成功！
2024-04-01 22:02:02,734 | INFO | mysql.py: 15|数据库查询结果为：{'id': 1, 'web': '急救云', 'key': 'url_api', 'value': 'http://systest.whsaviour.com/platform-admin'}
2024-04-01 22:02:02,735 | INFO | test_login.py: 71|***正在执行密码为空用例***
2024-04-01 22:02:02,735 | INFO | requests_utils.py: 7|发送请求的url为：http://systest.whsaviour.com/platform-admin/sys/login
2024-04-01 22:02:02,735 | INFO | requests_utils.py: 8|发送请求的method为：post
2024-04-01 22:02:02,735 | INFO | requests_utils.py: 9|发送请求的headers为：{'Content-Type': 'application/json'}
2024-04-01 22:02:02,735 | INFO | requests_utils.py: 10|发送请求的data为：{'username': 'admin', 'password': ''}
2024-04-01 22:02:02,781 | INFO | requests_utils.py: 23|响应状态码为：200
2024-04-01 22:02:02,781 | INFO | requests_utils.py: 24|响应success为：False
2024-04-01 22:02:02,782 | INFO | requests_utils.py: 25|响应message为：用户名或密码错误
2024-04-01 22:02:02,782 | INFO | test_login.py: 73|用例执行成功，请求的结果为：{'success': False, 'message': '用户名或密码错误', 'code': 500, 'result': None, 'resultList': None, 'timestamp': 1711980124837}
2024-04-01 22:02:02,783 | INFO | test_login.py: 88|用例断言成功
2024-04-01 22:02:03,062 | INFO | mysql.py: 28|执行sql语句成功！
2024-04-01 22:02:03,068 | INFO | mysql.py: 15|数据库查询结果为：{'id': 1, 'web': '急救云', 'key': 'url_api', 'value': 'http://systest.whsaviour.com/platform-admin'}
2024-04-01 22:02:03,068 | INFO | test_login.py: 71|***正在执行新增防控知识分类用例***
2024-04-01 22:02:03,068 | INFO | requests_utils.py: 7|发送请求的url为：http://systest.whsaviour.com/platform-admin/knowledgeClassification/add
2024-04-01 22:02:03,068 | INFO | requests_utils.py: 8|发送请求的method为：post
2024-04-01 22:02:03,068 | INFO | requests_utils.py: 9|发送请求的headers为：{'Content-Type': 'application/json'}
2024-04-01 22:02:03,068 | INFO | requests_utils.py: 10|发送请求的data为：{'name': '测试'}
2024-04-01 22:02:03,114 | INFO | requests_utils.py: 23|响应状态码为：500
2024-04-01 22:02:03,114 | INFO | test_login.py: 75|用例执行失败，请查看日志找原因。
2024-04-01 22:02:03,181 | INFO | mysql.py: 15|数据库查询结果为：{'id': 1, 'web': '急救云', 'key': 'url_api', 'value': 'http://systest.whsaviour.com/platform-admin'}
2024-04-01 22:02:03,181 | INFO | test_login.py: 71|***正在执行查询防控知识分类用例***
2024-04-01 22:02:03,181 | INFO | requests_utils.py: 7|发送请求的url为：http://systest.whsaviour.com/platform-admin/knowledgeClassification/list
2024-04-01 22:02:03,181 | INFO | requests_utils.py: 8|发送请求的method为：get
2024-04-01 22:02:03,181 | INFO | requests_utils.py: 9|发送请求的headers为：{'Content-Type': 'application/json'}
2024-04-01 22:02:03,181 | INFO | requests_utils.py: 10|发送请求的data为：{}
2024-04-01 22:02:03,226 | INFO | requests_utils.py: 23|响应状态码为：500
2024-04-01 22:02:03,226 | INFO | test_login.py: 75|用例执行失败，请查看日志找原因。
2024-04-01 22:02:03,238 | INFO | mysql.py: 15|数据库查询结果为：{'id': 1, 'web': '急救云', 'key': 'url_api', 'value': 'http://systest.whsaviour.com/platform-admin'}
2024-04-01 22:02:03,239 | INFO | test_login.py: 71|***正在执行编辑防控知识分类用例***
2024-04-01 22:02:03,239 | INFO | requests_utils.py: 7|发送请求的url为：http://systest.whsaviour.com/platform-admin/knowledgeClassification/edit
2024-04-01 22:02:03,239 | INFO | requests_utils.py: 8|发送请求的method为：put
2024-04-01 22:02:03,239 | INFO | requests_utils.py: 9|发送请求的headers为：{'Content-Type': 'application/json'}
2024-04-01 22:02:03,239 | INFO | requests_utils.py: 10|发送请求的data为：{'name': '测试123', 'id': '${id}'}
2024-04-01 22:02:03,292 | INFO | requests_utils.py: 23|响应状态码为：500
2024-04-01 22:02:03,292 | INFO | test_login.py: 75|用例执行失败，请查看日志找原因。
2024-04-01 22:02:03,302 | INFO | mysql.py: 15|数据库查询结果为：{'id': 1, 'web': '急救云', 'key': 'url_api', 'value': 'http://systest.whsaviour.com/platform-admin'}
2024-04-01 22:02:03,302 | INFO | test_login.py: 71|***正在执行删除防控知识分类用例***
2024-04-01 22:02:03,302 | INFO | requests_utils.py: 7|发送请求的url为：http://systest.whsaviour.com/platform-admin/knowledgeClassification/delete
2024-04-01 22:02:03,302 | INFO | requests_utils.py: 8|发送请求的method为：delete
2024-04-01 22:02:03,302 | INFO | requests_utils.py: 9|发送请求的headers为：{'Content-Type': 'application/json'}
2024-04-01 22:02:03,302 | INFO | requests_utils.py: 10|发送请求的data为：{'id': '${id}'}
2024-04-01 22:02:03,353 | INFO | requests_utils.py: 23|响应状态码为：500
2024-04-01 22:02:03,354 | INFO | test_login.py: 75|用例执行失败，请查看日志找原因。
2024-04-01 22:02:03,363 | INFO | test_login.py: 28|------执行测试结束，完成时间为：2024-04-01 22:02:02------
